services:
    web:
        image: "nginx:latest"
        container_name: nginx_container
        ports:
            - "8080:80"
        volumes:
            - ./html:/usr/share/nginx/html # arquivos que seram copiado/mapeados : onde seram colados/montados dentro do container
            - ./config/default.conf:/etc/nginx/conf.d/default.conf # Mesma coisa para o default.conf
