apiVersion: v1
kind: Pod
metadata:
    name: app-pod
    labels:
        name: app-pod
spec:
    containers:
        - name: app-container
          image: node:18
          env:
              - name: APP_ENV # Nome da variável de ambiente do container
                valueFrom:
                    configMapKeyRef:
                        name: app-config # Nome do ConfigMap
                        key: APP_ENV # Nome da chave do ConfigMap
              - name: APP_PORT
                valueFrom:
                    configMapKeyRef:
                        name: app-config
                        key: APP_PORT
              - name: DATABASE_URL
                valueFrom:
                    configMapKeyRef:
                        name: app-config
                        key: DATABASE_URL
          resources:
              limits:
                  memory: "128Mi"
                  cpu: "500m"
          command:
              [
                  "sh",
                  "-c",
                  "echo App running on $APP_PORT in $APP_ENV mode with DB $DATABASE_URL && sleep 3600",
              ]
