apiVersion: batch/v1 # Vers찾o que o Jub usa.
kind: Job
metadata:
    name: example-one-time-job
spec:
    template:
        spec:
            containers:
                - name: example
                  image: busybox
                  command: ["echo", "Hello K8s!"]
            restartPolicy: Never # Define qu o Job n찾o deve ser reiniciado ap처s falhar ou concluir.
    backoffLimit: 4 # Quantas vezes o Job pode tentar novamente ap처s falha
