apiVersion: v1
kind: Secret
metadata:
    name: my-secret
type: Opaque
data: # Defina os dados no formato chave: valor
    username: bXl1c2Vy # base64(myuser)
    password: bXlwYXNzd29yZA== # base64(mypassword)
