apiVersion: v1
kind: Pod
metadata:
    name: volume-secret-pod
    labels:
        name: volume-secret-pod
spec:
    containers:
        - name: node-container
          image: node:18
          volumeMounts:
              - name: secret-volume # Nome do volume
                mountPath: /etc/secret # Local onde o volume será montado dentro do container
                readOnly: true # Define se o volume é somente leitura
          resources:
              limits:
                  memory: "128Mi"
                  cpu: "500m"
    volumes:
        - name: secret-volume # Nome do volume
          secret:
              secretName: my-secret # Nome da Secret que contém os dados
