apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: cluster-admin
rules:
    - apiGroups: [""]
      resources: ["nodes", "namespaces"] # Controla os recursos de dentro do Cluster
      verbs: ["get", "list", "create", "delete"]
