apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: development
    name: pod-reader
rules:
    - apiGroups: [""] # "" indica a API central do K8s
      resources: ["pods"] # Recursos que o role pode acessar
      verbs: ["get", "list", "create"] # Ações que o role pode realizar
