apiVersion: apps/v1
kind: Deployment
metadata:
    name: blue-app
spec:
    selector:
        matchLabels:
            app: my-app
            version: blue
    template:
        metadata:
            labels:
                app: my-app
                version: blue
        spec:
            containers:
                - name: blue-app
                  image: nginx:1.10
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
