apiVersion: v1
kind: Service
metadata:
    name: blue-green
spec:
    selector:
        app: my-app # Nome das aplicações
        version: blue # Versão da aplicação, mude para "green" para realizar a troca
    ports:
        - port: 80
          targetPort: 8080
