apiVersion: apps/v1
kind: Deployment
metadata:
    name: green-app
spec:
    selector:
        matchLabels:
            app: my-app
            version: green
    template:
        metadata:
            labels:
                app: my-app
                version: green
        spec:
            containers:
                - name: green-app
                  image: nginx:1.20
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
