apiVersion: v1
kind: Pod
metadata:
    name: toleration-pod
    labels:
        name: toleration-pod
spec:
    tolerations:
        - key: "dedicated" # Mesma chave da taint
          operator: "Equal" # Define que a taint e a toleration devem ter o mesmo valor
          value: "financeiro" # Valor da taint
          effect: "NoSchedule" # Mesmo efeito da taint
    containers:
        - name: toleration-pod
          image: nginx:latest
          resources:
              limits:
                  memory: "128Mi"
                  cpu: "500m"
          ports:
              - containerPort: 80
