apiVersion: v1
kind: Pod
metadata:
    name: privileged-pod
    labels:
        name: privileged-pod
spec:
    containers:
        - name: privileged-container
          image: ubuntu
          command: ["sleep", "3600"]
          resources:
              limits:
                  memory: "128Mi"
                  cpu: "500m"
          securityContext:
              privileged: true
