apiVersion: networking.k8s.io/v1 # API usada pelo Ingress
kind: Ingress
metadata:
    name: my-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    ingressClassName: nginx
    rules:
        - host: app.127.0.0.1.nip.io # Baseado em HOST (app.)
          http:
              paths:
                  - pathType: Prefix
                    path: /
                    backend:
                        service:
                            name: app-service
                            port:
                                number: 80
        - host: 127.0.0.1.nip.io # Baseado em PATH (/api)
          http:
              paths:
                  - pathType: Prefix
                    path: /api
                    backend:
                        service:
                            name: api-service
                            port:
                                number: 80
