apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: myresource-rolebinding
    namespace: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: myresource-role
subjects:
    - kind: ServiceAccount
      name: myresource-sa
      namespace: default
