apiVersion: v1
kind: Pod
metadata:
    name: request-limits-pod
    labels:
        name: request-limits-pod
spec:
    containers:
        - name: request-limits-nginx-container
          image: nginx:latest
          resources:
              requests:
                  memory: "200Mi" # 200 Mebibyte
                  cpu: "500m" # 500 milicores
              limits:
                  memory: "400Mi"
                  cpu: "1000m"
          ports:
              - containerPort: 80
