apiVersion: v1
kind: Pod
metadata:
    name: my-pvc-pod
    labels:
        name: my-pvc-pod
spec:
    containers:
        - name: my-pvc-pod
          image: nginx
          resources:
              limits:
                  memory: "128Mi"
                  cpu: "500m"
          volumeMounts: # Configure o volume
              - mountPath: /data
                name: my-volume
    volumes:
        - name: my-volume
          persistentVolumeClaim: # Conectamos com o nosso PVC que aplica o CSI Driver no volume
              claimName: my-pvc
