apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: my-pdb
spec:
    minAvailable: 2 # Mínimo de pods disponíveis.
    selector:
        matchLabels:
            app: my-app # Nome do deploy ou pod.
